apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cncf-backstage-demo
  annotations:
    github.com/project-slug: mongamae-nioh/cncf-backstage-demo
spec:
  type: other
  lifecycle: unknown
  owner: mongamae-nioh
